<calculator>:

		    BoxLayout:
		    	id:Display
		    	orientation: 'vertical'
		    BoxLayout:
		    	id:main
		    	GridLayout:
		    		id: numbers
		    		cols: 3
		    	BoxLayout:
		    		id: symbols1
		    		orientation: 'vertical'
		            GridLayout:
		            	id: first 
		            	cols: 3
		        GridLayout:
		        	id:symbols2
		        	cols: 1
		    BoxLayout:
		    	id: statusbar
		    
